[package]
name = "move_gen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
rand = "0.8.5"
sdk = { path = "../sdk" }

[build-dependencies]
codegen = "0.2.0"
sdk = { path = "../sdk" }
