[package]
name = "sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
array-const-fn-init = "0.1.1"
bytemuck = "1.13.1"
colored = "2.0.0"
lazy_static = "1.4.0"
num_enum = "0.6.1"
rand = "0.8.5"
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
